appName: payment
replicaCount: 1
image:
  repository: 378784712135.dkr.ecr.us-east-1.amazonaws.com/payment
  pullPolicy: Always

serviceAccount:
  create: true
  annotations: {}

service:
  type: ClusterIP
  port: 80
  containerPort: 8080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi
env:
  name: prod

configmap:
  create: true
  content:
    CART_HOST: cart
    CART_PORT: "80"
    USER_HOST: user
    USER_PORT: "80"
    AMQP_HOST: rabbitmq
    AMQP_USER: roboshop
    AMQP_PASS: roboshop123

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
